### PR TITLE
Spark 3.3.0 support, gradle, and automate releasing all versions at once

### PR DESCRIPTION
**Pull request by Jolanrensen**
https://github.com/Kotlin/kotlin-spark-api/issues/167

### CODE REVIEW

**Comment by Jolanrensen** [comment]
Maybe also find a way for https://github.com/Kotlin/kotlin-spark-api/issues/166 here

**Review by asm0dey — APPROVED** [review]
I like the structure, but I would prefer to have this split into couple commits — one for migration maven—gradle, one for tests fixes, one for jcp maybe

**Comment by Jolanrensen** [comment]
> I like the structure, but I would prefer to have this split into couple commits — one for migration maven—gradle, one for tests fixes, one for jcp maybe

It's difficult to squash the older commits since this is already a combination of 2 or 3 pull requests. (The gradle branch, spark 3.0 support branch, main branch). Squashing with 2+ parents is impossible afaik

**Comment by Jolanrensen** [comment]
@asm0dey I want to update the wip commit message to:
```
Scala- and Spark version now controlled from gradle.properties or gradlew command. JCP is used for compatibilty issues across scala- and spark versions. JPC compatibility with IntelliJ is fixed. gradlew-all-versions can be used to push commands to all versions, gh actions uses matrix to deploy/build all of them. kotlin 1.7.10, updated readme.
```
But githut rejects my push for some reason

**Pull request merged**
