### PR TITLE
Update spark to 3.3.2

### PR DESCRIPTION
**Pull request by devongleeson**

### CODE REVIEW

**Comment by Jolanrensen** [comment]
Awesome! I suppose an update to 3.3.2 from 3.3.1 won't cause many issues. I did change your PR to target main instead of release, as that's common for this project. Please also update gradles.properties to Spark 3.3.2 as the project always targets the latest possible Spark version by default. I'll try and run the github actions that will perform the tests in a bit :)

**Comment by devongleeson** [comment]
Question: should this be updated? https://github.com/Kotlin/kotlin-spark-api/blob/release/core/build.gradle.kts#L30

**Comment by Jolanrensen** [comment]
> Question: should this be updated? https://github.com/Kotlin/kotlin-spark-api/blob/release/core/build.gradle.kts#L30
> 
> Looks like that logic lives in a few places in the project's build.

Looks like the tests pass for 3.3.2, so it seems that Spark fixed the issue. I do suspect the issue is still present for 3.3.1, so it can remain like that.

**Review by Jolanrensen — APPROVED** [review]

**Comment by Jolanrensen** [comment]
Thanks for the help! I'll probably publish 1.2.4 soon with spark 3.3.2 support and java 8 support for jupyter notebooks.

**Pull request merged**
